### ISSUE TITLE
RuntimeError: The size of tensor a (552) must match the size of tensor b (550) at non-singleton dimension 3

### ISSUE THREAD

**Issue by Heibaizhu** [FadeoN/Distilling-Image-Dehazing-With-Heterogeneous-Task-Imitation#1]
Excellent work! I meet the problem above when I use the Student class to predict haze free image. It seems the upsampling module may meet dismatch problem when the input size is not a multiple of 4?

**Comment by FadeoN** [comment]
It should be fixed with the new commit. Please try again.

**Comment by Heibaizhu** [comment]
It works! Thank you!
