### ISSUE TITLE
Test lists on O-HAZE dataset?

### ISSUE THREAD

**Issue by Fanbenchao** [FadeoN/Distilling-Image-Dehazing-With-Heterogeneous-Task-Imitation#2]
I'm very intersted in your work and compare the model performance with your model on the O-HAZE dataset. I have explore the NTIRE 2018 chanllenge for the test lists and couldn't find it. Could you provide the test lists on O-HAZE dataset? Thank you!

**Comment by FadeoN** [comment]
I trained the model on another dataset, so i do not know the test list.
