### ISSUE TITLE
No best model found

### ISSUE THREAD

**Issue by anothersin** [FadeoN/Distilling-Image-Dehazing-With-Heterogeneous-Task-Imitation#4]
when I run the train_teather.py,  the issue is caused 

No best model found at 'PATH TO STORE LOGS, CHECKPOİNTS, RESULTS/CheckPoints/O-Haze/teacher/29_10_2020_21_02_26/mode                                 l_best.pth'. Exiting...

where did i could find 'model_best.pth'?

**Comment by FadeoN** [comment]
Checkpoints are saved to the location you specify in config.ini.
