### ISSUE TITLE
The teacher network cannot reconstruct the original image

### ISSUE THREAD

**Issue by huahuasmi** [FadeoN/Distilling-Image-Dehazing-With-Heterogeneous-Task-Imitation#5]
Thanks for your great job.I have a questions about the teacher network.I can't reconstruct the gt image using other datasets. The output image is more blurred than the input.

**Comment by FadeoN** [comment]
Yeah, thats an issue i also faced with. I am not the author of the paper and could not find the issue, other than bad initialization. I trained the model with V100 for a long time, blur is gone after a while but still we should not train for that long, given the paper says that they trained for 30 epochs.  Feel free to send an email to original authors, If you figure out, why thats the case let me know.

**Comment by huahuasmi** [comment]
As Relu() in the network will clamp the value in [0,1],we figured out that if you normalize the image to [0,1] other than [-1,1] using normalize in the beginning.Then use (Tanh()+1)/2 in the last layer will solve the problem.

**Comment by FadeoN** [comment]
I actually tried that version but could not get the desired result. Let me know how yours go.

**Comment by hello-trouble** [comment]
> As Relu() in the network will clamp the value in [0,1],we figured out that if you normalize the image to [0,1] other than [-1,1] using normalize in the beginning.Then use (Tanh()+1)/2 in the last layer will solve the problem.

Thank you very much. Is the dataset of ITS  used in  training the teacher network in the paper ?   The paper proposed that  "ITS contains 13990 synthestic hazy image " , but the  dataset ITS I download includes about "100001" images .  I am puzzled about this thing, what's wrong with it ?

**Comment by hello-trouble** [comment]
> As Relu() in the network will clamp the value in [0,1],we figured out that if you normalize the image to [0,1] other than [-1,1] using normalize in the beginning.Then use (Tanh()+1)/2 in the last layer will solve the problem.
I am sorry to distureb you, but i am also puzzled about this problem.  Should I delele the normalize operation in transforms ,and use  (Tanh()+1)/2 in the last layer ?

**Comment by ssx119844** [comment]
Have you solved this problem?

**Comment by ssx119844** [comment]
> 由于网络中的Relu（）会将值限制在[0,1]中，因此我们发现，如果在开始时使用normalize将图像标准化为[-1,1]以外的[0,1]，然后使用（最后一层的Tanh（）+ 1）/ 2将解决此问题。

I didn't solve the problem. Could you provide the code of liberation plan？ Thanks.

**Comment by jjb202** [comment]
Hi, I would like to ask if the input to the teacher network is a clean and fog-free image? Which means input ground true?

**Comment by suzhipeng** [comment]
> > As Relu() in the network will clamp the value in [0,1],we figured out that if you normalize the image to [0,1] other than [-1,1] using normalize in the beginning.Then use (Tanh()+1)/2 in the last layer will solve the problem.
> > I am sorry to distureb you, but i am also puzzled about this problem.  Should I delele the normalize operation in transforms ,and use  (Tanh()+1)/2 in the last layer ?

Hi, I would like to ask if the input to the teacher network is a clean and fog-free image? Which means input ground true?

**Comment by FadeoN** [comment]
For the teacher network, both input and the output is clean image. Since it's sole purpose is the reconstruction.

**Comment by jjb202** [comment]
Since the input and output are clean, I can't understand what information he is reconstructing.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FadeoN/Distilling-Image-Dehazing-With-Heterogeneous-Task-Imitation"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月2日(星期二) 晚上6:40
收件人:&nbsp;"FadeoN/Distilling-Image-Dehazing-With-Heterogeneous-Task-Imitation"<Distilling-Image-Dehazing-With-Heterogeneous-Task-Imitation@noreply.github.com&gt;;
抄送:&nbsp;"ZhiPeng Su"<229602421@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [FadeoN/Distilling-Image-Dehazing-With-Heterogeneous-Task-Imitation] The teacher network cannot reconstruct the original image (#5)





 
For the teacher network, both input and the output is clean image. Since it's sole purpose is the reconstruction.

**Comment by FadeoN** [comment]
I suggest you to read the paper once again, It is argued that intermediate features that is obtain during reconstruction process can be useful for student network. Thus it reconstructs clean images from clean images.

**Comment by hello-trouble** [comment]
> For the teacher network, both input and the output is clean image. Since it's sole purpose is the reconstruction.

Thank you for your kind reply. Is  the ITS dataset used in training the teacher network ?

**Comment by FadeoN** [comment]
Yes, it is.

**Comment by hello-trouble** [comment]
> As Relu() in the network will clamp the value in [0,1],we figured out that if you normalize the image to [0,1] other than [-1,1] using normalize in the beginning.Then use (Tanh()+1)/2 in the last layer will solve the problem.

Because the default value of a tensor is in [0,1], should I remove the normalization operation ?   looking forword for your help.

**Comment by jjb202** [comment]
> Yeah, thats an issue i also faced with. I am not the author of the paper and could not find the issue, other than bad initialization. I trained the model with V100 for a long time, blur is gone after a while but still we should not train for that long, given the paper says that they trained for 30 epochs. Feel free to send an email to original authors, If you figure out, why thats the case let me know.

How long did you train for? How were the parameters set?
