### ISSUE TITLE
Why read the host name when reading the configuration file here？

### ISSUE THREAD

**Issue by littlealili** [FadeoN/Distilling-Image-Dehazing-With-Heterogeneous-Task-Imitation#6]
def read_config():
    config = cp.ConfigParser()
    cur_path = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    config.read(os.path.join(cur_path, 'config.ini'))
    host = socket.gethostname()
    return config[host]

**Comment by FadeoN** [comment]
I used that config to use different configs in different servers. Feel free to omit that part if you dont need it.

**Comment by littlealili** [comment]
When return config[host], there is an error :Exception has occurred: KeyError
'pc008'. Why?
